create table public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  city text,
  state text,
  zip_code text,
  point_of_contact text,
  id_cust text,
  email_contact text,
  company text
);

create index customers_name_idx on public.customers (name);
create index customers_id_cust_idx on public.customers (id_cust);
create index customers_company_idx on public.customers (company);
