alter table public.packing_lists
  drop constraint if exists packing_lists_customer_id_fkey;

alter table public.customers
  alter column id type bigint;

alter table public.customers
  alter column id add generated by default as identity;

alter table public.packing_lists
  alter column customer_id type bigint;

alter table public.packing_lists
  add constraint packing_lists_customer_id_fkey
  foreign key (customer_id) references public.customers (id);

select setval(
  pg_get_serial_sequence('public.customers', 'id'),
  coalesce((select max(id) from public.customers), 1)
);

